[build]
  command = "npm run build"
  publish = ".next"

[context.deploy-preview]
  command = "npm run build"
  publish = ".next"

[context.branch-deploy]
  command = "npm run build"
  publish = ".next"
